### PR TITLE
Ruby Update

### PR DESCRIPTION
**Pull request by amirahav**
This replaces ruby 2.1.x with Ruby 2.3.x to make it possible to use Berkshelf in mu-upload-chef-artifacts.
It also fixes some issues with Jenkins, and replaces the existing python snapshot script/cron job with a newer one.

**New mu-upload-chef-artifacts behavior** 
Will default to using Berkshelf to upload artifacts which solves multiple problems with the existing implementation (difficult to have the same dependency with multiple versions across multiple projects, overly dependent on the cookbooks MU includes by default, couldn't pull in repos from git directly)
If a Berksfile doesn't exist it will try to upload the cookbooks as before by staging them locally, however it can't resolve all the dependencies so best practice is create a Berksfile and add dependencies to your cookbooks.

If you are using a certificate generated by a certificate authority it will most likely not be trusted, and you will have to do one of two things - 
1. add the root certificate to the local root extract. 
OR 
2. Download and up to date extract from https://curl.haxx.se/docs/caextract.html  

Nothing needs to be done for MU's self signed cert other than run mu_setup.

**Ruby 2.3 upgrade**
This exposed some self referencing code in method decelerations, those should be fixed now.
Make sure to copy the RPMS and windows cygwin zip to your own bucket...

**New snapshot script behavior**
By default will now snapshot root volume, and exposes the following node attributes:
```
default['ebs_snapshots']['device_name'] = nil
default['ebs_snapshots']['days_to_keep'] = 15
default['ebs_snapshots']['exclude_devices'] = %w{/dev/xvdn /dev/xvdo /dev/xvdp /dev/xvdq xvdn xvdo xvdp xvdq}
```

### CODE REVIEW

**Comment by jstange** [comment]
I'm gonna pull this onto FEMA's master for testing. I'm about to merge my branch with the CentOS 7 Nagios fixes into master, and thus this, FYI. I think you might be the only other person it could affect, hopefully only positively.

**Comment by jstange** [comment]
Had to make a change to `mu-self-update` to get this to fly. It tries to do a `bundle install` before updating Ruby, and several of the gems aren't ok with that. Merged master plus that change.

**Comment by amirahav** [comment]
@jstange This is pull request if from my fork, so you will probably have to change the remote to pull in the changes. let me add that change to _mu-self-update_
 
Let me know if you'd like me to open another pull request to merge this into the berkshelf branch so you can more easily play around with this.

**Comment by amirahav** [comment]
@jstange The pull request should now be up to date with your two changes. 
Be careful about using cloudamatic/berkshelf without merging the remote, it has several issues, including pinning gems to older versions (_berkshelf_ shouldn't be pinned to _4.3_ anymore).

Sorry for the confusion!!

**Comment by jstange** [comment]
I hacked up the `.git/config` on this machine to use your remote for this branch before my meddling. If it pushed somewhere other than there, I don't know why. As a general tooling enhancement to `mu-self-update` though, that's super useful.

**Comment by jstange** [comment]
Sweet, the annoying problems around SSL appear to have been resolved. FEMA's `Berksfile` is no longer stuck with an intractable choice between communicating with Chef and communicating with any other SSL endpoint.

**Comment by amirahav** [comment]
Cool! good to hear that's working for you!

**Comment by jstange** [comment]
`mu-upload-chef-artifacts` isn't honoring `-n` and `-s`. I'll chase it down. I've been meaning to have a go at those flags anyway.

**Comment by amirahav** [comment]
I wounder what's different then. Just ran `-s` and saw only cookbooks being uploaded

**Comment by jstange** [comment]
It seems to do the right thing if you also give it `-r`, but if you omit that flag it barrels ahead and does roles, data bags, etc. Looks like we do each repo in its own complete pass now, and some flags are getting lost somewhere along the line so that at 2+ it behaves weird. Figuring it out and fixing now.

**Comment by amirahav** [comment]
That explains it - I have mostly been running with -r.
Doing each repo in its own complete pass is intentional - cross repo version conflicts was inconsistent and annoying, this way each repo can decide which version of a cookbook they want to enforce without being affected by upstream/downstream repos

**Comment by jstange** [comment]
Yeah, that's fine for now. This utility needs a reinvention and a rewrite in Ruby pretty badly, but now is not the opportunity.

I fixed that logic bug, and also added a new flag, `-m` (as in "match"). It is a kludge to expose the "just do one thing" arguments for `knife` and `berks`, respectively, so we don't have to upload the entire flippin' ecosystem during development. Give it a name, and it only uploads things with that name. It pays attention to `-s` and `-g` still so you can tighten that to cookbooks and data bags.

```
# mu-upload-chef-artifacts -n -m wp

Installing Berkshelf Chef cookbooks from /opt/mu/lib to Chef Server

Installing Berkshelf Chef cookbooks from /opt/mu/var/fema_platform to Chef Server
Working from /root
Uploading any non-cookbook items named 'wp'
Updated Role wp
Data bag nagios_services already exists
Updated data_bag_item[nagios_services::http_wordpress]
```

```
# mu-upload-chef-artifacts -n -m symantec

Installing Berkshelf Chef cookbooks from /opt/mu/lib to Chef Server

Installing Berkshelf Chef cookbooks from /opt/mu/var/fema_platform to Chef Server
Uploaded symantec (0.1.0) to: 'https://mu.femadata.com:7443/organizations/mu'
Working from /root
Uploading any non-cookbook items named 'symantec'
```

**Comment by jstange** [comment]
@rpattcorner This pull request passes my smell tests now. Full-throated testing should be done as soon as feasible so we can get it merged.

Things which are substantially altered:

- `mu-upload-chef-artifacts` has been stirred
- The internal version of Ruby has been bumped to 2.3 from 2.1
- Version bumps on `chef-client`, `chef-server`, and various gems (including `aws-sdk-core`)
- Our forked `chef-splunk` cookbook has been renamed to `mu-splunk`. Any platform repo cookbooks or Berksfiles that reference that cookbook by name will need to be updated.

Note that this branch is on @amirahav's remote, not the cloudamatic one. I had to manually manipulate my `/opt/mu/lib/.git/config` to point it to the right thing:

```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        fetch = +refs/heads/*:refs/remotes/origin/*
        url = git@github.com:cloudamatic/mu.git
[remote "amirahav"]
        fetch = +refs/heads/*:refs/remotes/amirahav/*
        url = git@github.com:amirahav/mu.git
[branch "master"]
        remote = origin
        merge = refs/heads/master
[branch "windows_bootstrap_stupidity"]
        remote = origin
        merge = refs/heads/windows_bootstrap_stupidity
[branch "berkshelf"]
        remote = amirahav
        merge = refs/heads/berkshelf
```

I've removed the extraneous branch named `berkshelf` from our org to minimize confusion.

**Pull request closed without merging**
