### PR TITLE
AWS NAT #2

### PR DESCRIPTION
**Pull request by amirahav**
This fixes some issues with the previous pull request.

Adding support for VPC NAT Gatways and endpoints.
VPC NATs provide a replacement to an instance NAT when it isn't needed as a bastion. 
VPC endpoints allows to route traffic to S3 directly without having to route through a NAT or an Internet gateway.
See demo/vpc-aws-nat-endpoint.yaml for an example

This also upgrades the Tomcat cookbook, fixes an issue with findFreeElasticIp.

### CODE REVIEW

**Comment by jstange** [comment]
Tell you what, I'm going to push to replace our EC2 instance NATs in FEMA's operation with these using this branch, and use that as an excuse for testing. Stand by for feedback when I get that pushed through.

**Comment by rpattcorner** [comment]
Sounds great!

Robert Patt-Corner
3865 Wilson Blvd, Suite 500.  Arlington, VA 22203.
t: (703) 652-0991  m: (410) 775-8096  f: (703) 842-7591
robert.patt-corner@eglobaltech.com<mailto:robert.patt-corner@eglobaltech.com>

[cid:image001.png@01CF7FF9.07C3F220]
www.eglobaltech.com<http://www.eglobaltech.com/>

**Comment by amirahav** [comment]
Cool, Thanks!

**Comment by jstange** [comment]
Ended up reading this so I could mirror the implementation over in *cloudformation_emitter* (93c59b9f531afb995c1ab63d1a188362305181d7). Looks fine to me, though I can't test it the way I wanted to in FEMA since it's married to VPC route/subnet creation.

Any reason you can think of not to have a '#NAT' route automatically set _create_nat_gateway_ to true in the config parser?

**Comment by jstange** [comment]
...wait, dumb question, you already thought of that and did that exact thing. Fine with me. I'm going to do a quick test deploy or two, then merge this.

**Comment by amirahav** [comment]
Just a quick comment on this one - I noticed yesterday that it won't work if you replace a NAT instance with a NAT gateway in an existing deploy because It's looking for the 'create_nat_gateway' attribute in the existing config, which obviously doesn't exist. 
I'll commit a fix to master hopefully later today.

**Pull request merged**
