### PR TITLE
Nuisances

### PR DESCRIPTION
**Pull request by jstange**
- `StoragePool` security groups should correctly associate with mountpoints
- Handle EC2 Classic Mu Master security group correctly
- Fix validator on `Notification`
- Fix validator on `Alarm`
- Somewhat more sensible defaulting on `Database` resources

### CODE REVIEW

**Comment by ryantiger658** [comment]
@jstange is there anything we can do to fix the 4 new Codeclimate issues?

**Comment by jstange** [comment]
Fixed the one that was an actual problem. Its other complaints are stupid.

**Comment by ryantiger658** [comment]
Sounds good. Just wanted to make sure we are looking at them.

**Comment by jstange** [comment]
Yeah, we should be, as much as I want to grump about it. We still need to sit down and tune Rubocop to some best practices defined by grownups. Far as I can tell its defaults are geared toward Rails bootcamp students.

**Comment by ryantiger658** [comment]
I have a branch fixing (most) of the Chef Foodcritic problems. I just need to get time to test and merge. 

I am hoping someone a little more versed in ruby will take point on the Rubocop issues.

**Comment by ryantiger658** [comment]
Closes CLOUDMATIC-160

**Pull request merged**
